// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jauuzzwtbbnyundldozd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImphdXV6end0YmJueXVuZGxkb3pkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzNTA3NzUsImV4cCI6MjA2MTkyNjc3NX0.xjXMop49-b1yvBJcL6RdSbxDQtkXZVMfOBQtbYpey04";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);